project:
  type: book

book:
  title: "Spatial-r: Tutorials on spatial data analysis in R"
  author: 
  - name: "Romain Frelat"
    orcid: "0000-0002-8631-4398"
    affiliations: 
    - name: FRB-CESAB
      url: "https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/"
  date: today

  page-footer: 
    left: "&copy; CC-By [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/FRBCesab/spatial-r)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true

  chapters:
    - index.qmd
    - chapters/01_intro.qmd
    - part: "Half-day 1"
      chapters: 
      - chapters/10_presentation_gis.qmd
      - chapters/11_vectors.qmd
      - chapters/12_rasters.qmd
      - chapters/13_extract.qmd
    - part: "Half-day 2"
      chapters:
      - chapters/20_presentation_data.qmd
      - chapters/21_multilayer.qmd
      - chapters/22_interactivemap.qmd
    - part: "Extra"
      chapters:
      - chapters/31_toydata_mpl.qmd
    - references.qmd

  reader-mode: false
  search: false

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
      - css/styles.scss
    code-copy: true
    code-line-numbers: false

execute:
  freeze: auto

