project:
  type: book

book:
  title: "Spatial-r: Tutorials on spatial data analysis in R"
  author: 
  - name: "Romain Frelat"
    orcid: "0000-0002-8631-4398"
    affiliations: 
    - name: FRB-CESAB
      url: "https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/"
  date: today
  
  page-footer: 
    left: "&copy; CC-By [FRB-CESAB](https://www.fondationbiodiversite.fr/en/about-the-foundation/le-cesab/)"
    center: "Code source available on [{{< fa brands github >}}](https://github.com/FRBCesab/spatial-r)"
    right: "Built with [Quarto](https://quarto.org/)"
    border: true

  chapters:
    - index.qmd
    - chapters/01_setup.qmd
    - chapters/02_presentation_gis.qmd
    - part: "Vectors"
      chapters: 
      #- chapters/10_vectors.qmd
      - chapters/11_points.qmd
      - chapters/12_lines.qmd
      - chapters/13_polygons.qmd
    - part: "Rasters"
      chapters:
      - chapters/21_rasters.qmd
      - chapters/22_multilayer.qmd
      - chapters/23_grid.qmd
    - part: "Extra"
      chapters:
      - chapters/31_toydata_mpl.qmd
    - references.qmd

  reader-mode: false
  search: true
  repo-url: https://github.com/FRBCesab/spatial-r/
  repo-actions: [issue]

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
      - css/styles.scss
    code-copy: true
    code-line-numbers: false

execute:
  freeze: auto

